apiVersion: v1
kind: Config
clusters:
  - name: mcaas-cluster
    cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzT0RRNE5qTXpNekV3SGhjTk1qWXdOekkwTURJeU1qRXhXaGNOTXpZd056SXhNREl5TWpFeApXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzT0RRNE5qTXpNekV3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFUV1Byc3NaV2NMeTlWdFNNazdNSnVFbTdya0l6TEdsK05IMXNrNXJYYmUKL1U5WU1uUUdyVWs5dmV0bWhWZUVxMUl5RUdrRHZsKzRJempQZll2cUZWaW5vMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXRCZEEzZXgxNTllQW41aUZQcmpyCmtZMFNyMDR3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQUtCSUpZN29oUUxROGxZL05nUVdlQU41eFEwc0UwYzgKVVRnL0ZVYTV4YXFqQWlCSmRaWnpOMmR1c0swa25tbGRTVkQ2YjczN3FYMVJHSHRDSGVLVFR0c1pEdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      server: https://127.0.0.1:6443
contexts:
  - name: mcaas-context
    context:
      cluster: mcaas-cluster
      user: github-actions-deployer
current-context: mcaas-context
users:
  - name: github-actions-deployer
    user:
      token: eyJhbGciOiJSUzI1NiIsImtpZCI6IktUeGViUFdZMWRfMXBTUUdfMkZ6YWZSYmZaSzdmcVhTVnpkZGtWYkF0VkEifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJrM3MiXSwiZXhwIjoxODE2NDAwMTUwLCJpYXQiOjE3ODQ4NjQxNTAsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiZGExNjYyYzYtODZmZS00MTNjLTk3NmEtMDg1OGZjZjE0YWE1Iiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJnaXRodWItYWN0aW9ucy1kZXBsb3llciIsInVpZCI6Ijk4YTgxMzIyLTU4ZWYtNGE4ZS05OWMzLWVjMjhhMmJjZmEyNSJ9fSwibmJmIjoxNzg0ODY0MTUwLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06Z2l0aHViLWFjdGlvbnMtZGVwbG95ZXIifQ.NTbluehXyO5JipDqxFaBBBvuvDUsigubQAxnxxUiaVuYCLSrPL6HhwHBBvpqzVneH_Nn__S9fs-RMlhzixqA3apdcWkE6S6__I6ee5HtgWmXDcFnvvorDBQ4SWOc4nfuw5wnpd3uPhV_pH140uW_wa12mjUDAmZpGOdEN5ZzsnulvCbPxNcKQRBogIlpaKm7a6WtH-92mJlRRTRE1DzkzGCqrtqgldRED0ze4cSg9SInxMeGBUaZDZGP624zRb6VvW1Lk5HYgOALJEQ6lGnrfR00IZdrX6d42zh6lBWyy-mlZ1CH7QJhsA-nXrDve-5-Ru4nmE0Hg4DSmpyUsI2zEg
