client:
  name: "testcustomer"
  display_name: "Test Customer"
  domain: "testcustomer.socom.co.il"
  prefix: "testcustomer"
  namespaces:
    managed-it: "testcustomer-managed-it"
    security-ops: "testcustomer-security-ops"
    grc: "testcustomer-grc"
    wazuh: "testcustomer-wazuh"
  wazuh_version: "4.14.6"
  database_name: "testcustomer_db"
  ingress:
    zammad_host: "alala.testcustomer.socom.co.il"
    ciso_host: "strategos.testcustomer.socom.co.il"
    shuffle_host: "kydoimos.testcustomer.socom.co.il"
    wazuh_host: "deimos.testcustomer.socom.co.il"