singleNode: true
extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: "mcaas-opensearch-secret"
        key: "opensearch-password"
persistence:
  enabled: true
  size: 20Gi
