fullnameOverride: shuffle

# Disable the chart's built-in OpenSearch since we use our standalone instance
opensearch:
  enabled: false

backend:
  openSearch:
    url: "http://mcaas-opensearch.security-ops.svc.cluster.local:9200"
    username: admin
    skipSSLVerify: true
  extraEnvVarsSecret: mcaas-opensearch-secret

orborus:
  enabled: true
  persistence:
    enabled: true
    size: 10Gi
