client:
  name: "demo"
  display_name: "Demo Client"
  domain: "demo.mcaas.example.com"
  prefix: "demo"
  namespaces:
    managed-it: "demo-managed-it"
    security-ops: "demo-security-ops"
    grc: "demo-grc"
    wazuh: "demo-wazuh"
  wazuh_version: "4.14.6"
  database_name: "demo_db"
  ingress:
    zammad_host: "alala.demo.mcaas.example.com"
    ciso_host: "strategos.demo.mcaas.example.com"
    shuffle_host: "kydoimos.demo.mcaas.example.com"
    wazuh_host: "deimos.demo.mcaas.example.com"