apiVersion: v1
kind: Namespace
metadata:
  name: demo-security-ops
---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-managed-it
---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-grc
---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-wazuh