name: Health Check MCaaS

on:
  workflow_dispatch: {}

jobs:
  health-check:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubeconfig
        shell: bash
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Check Kubernetes cluster connectivity
        run: kubectl cluster-info