apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/restartedAt: "2026-07-26T04:55:04+03:00"
  creationTimestamp: "2026-07-26T01:55:04Z"
  generateName: wazuh-manager-master-
  generation: 1
  labels:
    app: wazuh-manager
    apps.kubernetes.io/pod-index: "0"
    controller-revision-hash: wazuh-manager-master-5f7c8f648d
    node-type: master
    statefulset.kubernetes.io/pod-name: wazuh-manager-master-0
  name: wazuh-manager-master-0
  namespace: wazuh
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: wazuh-manager-master
    uid: 7aee32d1-aaea-4afa-9916-1980d8c22312
  resourceVersion: "28381"
  uid: 27abd598-fa5f-40d9-abf9-c0fecf56799f
spec:
  containers:
  - image: wazuh/wazuh-manager:4.14.6
    imagePullPolicy: IfNotPresent
    name: wazuh-manager
    resources:
      limits:
        cpu: 400m
        memory: 2Gi
      requests:
        cpu: 400m
        memory: 2Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-sw4bs
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: wazuh-manager-master-0
  nodeName: desktop-6j34ivf
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 101
  serviceAccount: default
  serviceAccountName: default
  subdomain: wazuh-cluster
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: wazuh-manager-master
    persistentVolumeClaim:
      claimName: wazuh-manager-master-wazuh-manager-master-0
  - configMap:
      defaultMode: 420
      name: wazuh-conf-2t66md6694
    name: config
  - name: filebeat-certs
    secret:
      defaultMode: 420
      secretName: indexer-certs-9h4d9gttmf
  - name: wazuh-authd-pass
    secret:
      defaultMode: 420
      secretName: wazuh-authd-pass
  - name: kube-api-access-sw4bs
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  allocatedResources:
    cpu: 400m
    memory: 2Gi
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-07-26T01:55:05Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-07-26T01:55:04Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-07-26T01:55:05Z"
    observedGeneration: 1
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-07-26T01:55:05Z"
    observedGeneration: 1
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-07-26T01:55:04Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - allocatedResources:
      cpu: 400m
      memory: 2Gi
    containerID: containerd://5b4dc8862d7b7f5ccf316fa77da5d9807941e421bda61de48db405c0b67bf8b9
    image: docker.io/wazuh/wazuh-manager:4.14.6
    imageID: docker.io/wazuh/wazuh-manager@sha256:f72a63b5a93c54b3b99bacc463de9217b19de674aa7413016ec4f3d0ff975dda
    lastState: {}
    name: wazuh-manager
    ready: true
    resources:
      limits:
        cpu: 400m
        memory: 2Gi
      requests:
        cpu: 400m
        memory: 2Gi
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-07-26T01:55:05Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        - 101
        uid: 0
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-sw4bs
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.127.2
  hostIPs:
  - ip: 192.168.127.2
  observedGeneration: 1
  phase: Running
  podIP: 10.42.0.105
  podIPs:
  - ip: 10.42.0.105
  qosClass: Guaranteed
  resources:
    limits:
      cpu: 400m
      memory: 2Gi
    requests:
      cpu: 386m
      memory: 2Gi
  startTime: "2026-07-26T01:55:04Z"
